### ISSUE TITLE
While the integrated test data opens on local install, uploaded data gives errors.

### ISSUE THREAD

**Issue by Daeveb** [KerryAM-R/ggVolcanoR#2]
I uploaded the proteomics data from your repository (ggVolcanoR/inst/extdata/Proteomics data.csv)  as a test using "own" data, after a file we generated here (correct 3 column headings, in .csv format) gave these same errors.  Tested on a couple of R installs on different systems (PC/Mac).

Listening on http://127.0.0.1:4122
Warning: Error in :: argument of length 0
  [No stack trace available]
Warning: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning: Error in if: missing value where TRUE/FALSE needed
  [No stack trace available]
Warning: Error in if: missing value where TRUE/FALSE needed
  [No stack trace available]
Warning: Error in if: missing value where TRUE/FALSE needed
  [No stack trace available]
Warning: Error in if: missing value where TRUE/FALSE needed
  [No stack trace available]
Warning: Error in if: missing value where TRUE/FALSE needed
  [No stack trace available]
Warning: Error in if: missing value where TRUE/FALSE needed
  [No stack trace available]
Warning: Error in if: missing value where TRUE/FALSE needed
  [No stack trace available]
Warning: Error in if: missing value where TRUE/FALSE needed
  [No stack trace available]

**Comment by KerryAM-R** [comment]
Hi Daeveb, 

Thanks for reporting this issue. 

1. comes up temporarily when the data is loading. 
Warning: Error in :: argument of length 0 
[No stack trace available]

2. Does not interfere with the plotting of the graphs. 
Warning: guides(<scale> = FALSE) is deprecated. Please use guides(<scale> = "none") instead.

3. Error to resolve
`Warning: Error in if: missing value where TRUE/FALSE needed
[No stack trace available]`

Thanks for identifying this. It was caused by the second refined.list.csv not being uploaded. I added in a second switch variable for this second file

`selectInput("dataset_list", "Choose a list-dataset:", choices = c("test-data-list", "own_list")),`

However it still appears if the file is missing with the Selected.ID drop down. I need see if I can use the validate function to change this to 'upload list of values' 

While I did a lot of testing with the web application, I didn't have anyone test the installation of the local version. So I very much appreciate your feedback :) 

Please let me know if this still hasn't resolved the issue.

**Comment by Daeveb** [comment]
Hi,

It looks like it is working now, I can open a datafile that is uploaded.
A couple of warnings but nothing gamestopping.  I'll play with the rest it over the next week or so and if I notice anything else I'll let you know.  Thanks again.

Warning: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.

**Comment by KerryAM-R** [comment]
Thank you for testing the application local version.
